/**
 * Automated Threat Hunting Service
 * 
 * AI-powered threat hunting service with ML-driven hypothesis generation,
 * automated hunt workflows, and predictive threat detection capabilities.
 * 
 * Features:
 * - ML-driven hypothesis generation from threat patterns
 * - Automated threat hunting workflows
 * - Deep learning for unknown threat pattern detection
 * - Predictive threat hunting with early warning systems
 * - Real-time hunt execution and result analysis
 * - Continuous learning from hunting outcomes
 * 
 * @author TrustHire Security Team
 * @version 3.0.0
 */

import { EventEmitter } from 'events';

// ============================================================================
// INTERFACES
// ============================================================================

/**
 * Threat hunting hypothesis generated by AI models
 */
export interface HuntingHypothesis {
  id: string;
  title: string;
  description: string;
  category: 'malware' | 'phishing' | 'apt' | 'insider' | 'ransomware' | 'data_exfiltration';
  confidence: number; // 0-1
  priority: 'low' | 'medium' | 'high' | 'critical';
  indicators: string[];
  tactics: string[]; // MITRE ATT&CK tactics
  techniques: string[]; // MITRE ATT&CK techniques
  generatedAt: Date;
  expiresAt: Date;
  status: 'active' | 'testing' | 'validated' | 'false_positive' | 'expired';
  huntQueries: HuntQuery[];
  predictedImpact: {
    likelihood: number;
    potentialDamage: 'low' | 'medium' | 'high' | 'critical';
    affectedAssets: number;
    estimatedCost: number;
  };
}

/**
 * Automated hunt query for hypothesis validation
 */
export interface HuntQuery {
  id: string;
  name: string;
  description: string;
  queryType: 'sql' | 'siem' | 'edr' | 'network' | 'log' | 'custom';
  query: string;
  dataSource: string;
  parameters: Record<string, any>;
  expectedResults: {
    minCount?: number;
    maxCount?: number;
    patterns?: string[];
    timeWindow?: string;
  };
  executionPlan: {
    schedule: string;
    retryPolicy: {
      maxRetries: number;
      backoffMultiplier: number;
    };
    timeout: number;
  };
}

/**
 * Automated threat hunting workflow
 */
export interface HuntingWorkflow {
  id: string;
  name: string;
  description: string;
  hypothesisId: string;
  status: 'pending' | 'running' | 'completed' | 'failed' | 'paused';
  createdAt: Date;
  startedAt?: Date;
  completedAt?: Date;
  queries: HuntExecution[];
  results: HuntResult[];
  findings: HuntFinding[];
  confidence: number;
  automatedActions: AutomatedAction[];
  nextExecution?: Date;
  schedule: {
    frequency: 'once' | 'hourly' | 'daily' | 'weekly' | 'monthly';
    interval: number;
    timezone: string;
  };
  huntQueries: HuntQuery[];
}

/**
 * Individual hunt query execution
 */
export interface HuntExecution {
  id: string;
  queryId: string;
  workflowId: string;
  status: 'pending' | 'running' | 'completed' | 'failed' | 'timeout';
  startedAt: Date;
  completedAt?: Date;
  duration?: number;
  resultCount: number;
  errorMessage?: string;
  executionContext: {
    dataSource: string;
    parameters: Record<string, any>;
    environment: string;
  };
}

/**
 * Results from hunt query execution
 */
export interface HuntResult {
  id: string;
  executionId: string;
  queryId: string;
  workflowId: string;
  timestamp: Date;
  dataSource: string;
  recordCount: number;
  data: any[]; // Raw query results
  summary: {
    keyFindings: string[];
    anomalies: string[];
    patterns: string[];
    riskLevel: 'low' | 'medium' | 'high' | 'critical';
  };
  metadata: {
    queryExecutionTime: number;
    dataQuality: 'excellent' | 'good' | 'fair' | 'poor';
    completeness: number; // 0-1
    freshness: number; // 0-1 (how recent is the data)
  };
}

/**
 * Security findings from hunt analysis
 */
export interface HuntFinding {
  id: string;
  workflowId: string;
  resultId: string;
  title: string;
  description: string;
  severity: 'info' | 'low' | 'medium' | 'high' | 'critical';
  confidence: number;
  category: string;
  indicators: Indicator[];
  timeline: TimelineEvent[];
  affectedAssets: Asset[];
  recommendations: string[];
  status: 'new' | 'investigating' | 'confirmed' | 'false_positive' | 'resolved';
  assignedTo?: string;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Security indicator from hunt findings
 */
export interface Indicator {
  type: 'ip' | 'domain' | 'url' | 'hash' | 'email' | 'file' | 'registry' | 'process';
  value: string;
  confidence: number;
  source: string;
  firstSeen: Date;
  lastSeen: Date;
  context: Record<string, any>;
}

/**
 * Timeline event for threat analysis
 */
export interface TimelineEvent {
  timestamp: Date;
  event: string;
  description: string;
  severity: 'info' | 'low' | 'medium' | 'high' | 'critical';
  source: string;
  evidence?: any;
}

/**
 * Affected asset information
 */
export interface Asset {
  id: string;
  name: string;
  type: 'server' | 'workstation' | 'network' | 'application' | 'database' | 'user';
  criticality: 'low' | 'medium' | 'high' | 'critical';
  location: string;
  owner?: string;
  riskScore: number;
}

/**
 * Automated response action
 */
export interface AutomatedAction {
  id: string;
  workflowId: string;
  findingId?: string;
  type: 'containment' | 'remediation' | 'notification' | 'escalation' | 'investigation';
  action: string;
  target: string;
  parameters: Record<string, any>;
  status: 'pending' | 'executing' | 'completed' | 'failed';
  executedAt?: Date;
  result?: any;
  errorMessage?: string;
}

/**
 * ML model configuration for hypothesis generation
 */
export interface MLModelConfig {
  modelType: 'neural_network' | 'random_forest' | 'gradient_boosting' | 'lstm' | 'transformer';
  version: string;
  parameters: Record<string, any>;
  trainingData: {
    sources: string[];
    timeRange: string;
    features: string[];
  };
  performance: {
    accuracy: number;
    precision: number;
    recall: number;
    f1Score: number;
  };
  lastTrained: Date;
  nextRetraining: Date;
}

/**
 * Service configuration
 */
export interface AutomatedHuntingConfig {
  enabled: boolean;
  hypothesisGeneration: {
    enabled: boolean;
    frequency: number; // minutes
    confidenceThreshold: number;
    maxActiveHypotheses: number;
    mlModels: MLModelConfig[];
  };
  automatedWorkflows: {
    enabled: boolean;
    maxConcurrentWorkflows: number;
    defaultTimeout: number;
    retryAttempts: number;
  };
  dataSources: {
    siem: DataSourceConfig;
    edr: DataSourceConfig;
    network: DataSourceConfig;
    logs: DataSourceConfig;
  };
  notifications: {
    enabled: boolean;
    channels: string[];
    severityThreshold: 'medium' | 'high' | 'critical';
  };
}

/**
 * Data source configuration
 */
export interface DataSourceConfig {
  enabled: boolean;
  connectionString: string;
  queryTimeout: number;
  maxConnections: number;
  retryPolicy: {
    maxRetries: number;
    backoffMultiplier: number;
  };
}

// ============================================================================
// MAIN SERVICE CLASS
// ============================================================================

/**
 * Automated Threat Hunting Service
 * 
 * Provides AI-powered threat hunting capabilities with ML-driven hypothesis
 * generation, automated workflows, and predictive threat detection.
 */
export class AutomatedHuntingService extends EventEmitter {
  private hypotheses: Map<string, HuntingHypothesis> = new Map();
  private workflows: Map<string, HuntingWorkflow> = new Map();
  private findings: Map<string, HuntFinding> = new Map();
  private config!: AutomatedHuntingConfig;
  private isRunning: boolean = false;
  private hypothesisGenerationInterval?: NodeJS.Timeout;
  private workflowExecutionInterval?: NodeJS.Timeout;

  constructor(config?: Partial<AutomatedHuntingConfig>) {
    super();
    this.config = this.mergeConfig(config);
    this.initializeService();
  }

  /**
   * Initialize the automated hunting service
   */
  private initializeService(): void {
    console.log('Initializing Automated Threat Hunting Service...');
    
    // Load existing hypotheses and workflows
    this.loadExistingData();
    
    // Start automated processes
    if (this.config.enabled) {
      this.startAutomatedProcesses();
    }
    
    console.log('Automated Threat Hunting Service initialized successfully');
  }

  /**
   * Start automated threat hunting processes
   */
  public start(): void {
    if (this.isRunning) {
      console.log('Automated hunting service is already running');
      return;
    }

    console.log('Starting automated threat hunting processes...');
    this.isRunning = true;
    
    // Start hypothesis generation
    if (this.config.hypothesisGeneration.enabled) {
      this.startHypothesisGeneration();
    }
    
    // Start workflow execution
    if (this.config.automatedWorkflows.enabled) {
      this.startWorkflowExecution();
    }
    
    this.emit('service:started');
    console.log('Automated threat hunting processes started');
  }

  /**
   * Stop automated threat hunting processes
   */
  public stop(): void {
    if (!this.isRunning) {
      console.log('Automated hunting service is not running');
      return;
    }

    console.log('Stopping automated threat hunting processes...');
    this.isRunning = false;
    
    // Clear intervals
    if (this.hypothesisGenerationInterval) {
      clearInterval(this.hypothesisGenerationInterval);
    }
    
    if (this.workflowExecutionInterval) {
      clearInterval(this.workflowExecutionInterval);
    }
    
    this.emit('service:stopped');
    console.log('Automated threat hunting processes stopped');
  }

  /**
   * Generate new hunting hypotheses using ML models
   */
  public async generateHypotheses(): Promise<HuntingHypothesis[]> {
    console.log('Generating new threat hunting hypotheses...');
    
    const hypotheses: HuntingHypothesis[] = [];
    
    try {
      // Analyze recent threat data
      const threatData = await this.analyzeRecentThreatData();
      
      // Generate hypotheses for each ML model
      for (const model of this.config.hypothesisGeneration.mlModels) {
        const modelHypotheses = await this.generateHypothesesWithModel(model, threatData);
        hypotheses.push(...modelHypotheses);
      }
      
      // Filter and prioritize hypotheses
      const filteredHypotheses = this.filterAndPrioritizeHypotheses(hypotheses);
      
      // Store new hypotheses
      for (const hypothesis of filteredHypotheses) {
        this.hypotheses.set(hypothesis.id, hypothesis);
        this.emit('hypothesis:generated', hypothesis);
      }
      
      console.log(`Generated ${filteredHypotheses.length} new hypotheses`);
      return filteredHypotheses;
    } catch (error) {
      console.error('Error generating hypotheses:', error);
      throw error;
    }
  }

  /**
   * Execute automated hunting workflows
   */
  public async executeWorkflows(): Promise<HuntingWorkflow[]> {
    console.log('Executing automated hunting workflows...');
    
    const executedWorkflows: HuntingWorkflow[] = [];
    
    try {
      // Get workflows ready for execution
      const readyWorkflows = this.getWorkflowsReadyForExecution();
      
      // Execute workflows with concurrency limit
      const maxConcurrent = this.config.automatedWorkflows.maxConcurrentWorkflows;
      const executingWorkflows = readyWorkflows.slice(0, maxConcurrent);
      
      for (const workflow of executingWorkflows) {
        try {
          const executedWorkflow = await this.executeWorkflow(workflow);
          executedWorkflows.push(executedWorkflow);
        } catch (error) {
          console.error(`Error executing workflow ${workflow.id}:`, error);
          workflow.status = 'failed';
          this.emit('workflow:failed', workflow);
        }
      }
      
      console.log(`Executed ${executedWorkflows.length} workflows`);
      return executedWorkflows;
    } catch (error) {
      console.error('Error executing workflows:', error);
      throw error;
    }
  }

  /**
   * Create a new hunting hypothesis
   */
  public async createHypothesis(hypothesisData: Partial<HuntingHypothesis>): Promise<HuntingHypothesis> {
    const hypothesis: HuntingHypothesis = {
      id: crypto.randomUUID(),
      title: hypothesisData.title || 'New Hypothesis',
      description: hypothesisData.description || '',
      category: hypothesisData.category || 'malware',
      confidence: hypothesisData.confidence || 0.5,
      priority: hypothesisData.priority || 'medium',
      indicators: hypothesisData.indicators || [],
      tactics: hypothesisData.tactics || [],
      techniques: hypothesisData.techniques || [],
      generatedAt: new Date(),
      expiresAt: hypothesisData.expiresAt || new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days
      status: 'active',
      huntQueries: hypothesisData.huntQueries || [],
      predictedImpact: hypothesisData.predictedImpact || {
        likelihood: 0.5,
        potentialDamage: 'medium',
        affectedAssets: 0,
        estimatedCost: 0
      }
    };

    this.hypotheses.set(hypothesis.id, hypothesis);
    this.emit('hypothesis:created', hypothesis);
    
    return hypothesis;
  }

  /**
   * Create automated hunting workflow
   */
  public async createWorkflow(workflowData: Partial<HuntingWorkflow>): Promise<HuntingWorkflow> {
    const workflow: HuntingWorkflow = {
      id: crypto.randomUUID(),
      name: workflowData.name || 'New Workflow',
      description: workflowData.description || '',
      hypothesisId: workflowData.hypothesisId || '',
      status: 'pending',
      createdAt: new Date(),
      queries: [],
      results: [],
      findings: [],
      confidence: 0,
      automatedActions: [],
      schedule: workflowData.schedule || {
        frequency: 'once',
        interval: 1,
        timezone: 'UTC'
      },
      huntQueries: []
    };

    this.workflows.set(workflow.id, workflow);
    this.emit('workflow:created', workflow);
    
    return workflow;
  }

  /**
   * Get active hypotheses
   */
  public getActiveHypotheses(): HuntingHypothesis[] {
    return Array.from(this.hypotheses.values())
      .filter(h => h.status === 'active' && h.expiresAt > new Date())
      .sort((a, b) => {
        const priorityOrder = { critical: 4, high: 3, medium: 2, low: 1 };
        return priorityOrder[b.priority] - priorityOrder[a.priority];
      });
  }

  /**
   * Get hunting workflows by status
   */
  public getWorkflowsByStatus(status: HuntingWorkflow['status']): HuntingWorkflow[] {
    return Array.from(this.workflows.values())
      .filter(w => w.status === status)
      .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
  }

  /**
   * Get recent findings
   */
  public getRecentFindings(limit: number = 50): HuntFinding[] {
    return Array.from(this.findings.values())
      .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())
      .slice(0, limit);
  }

  /**
   * Get hunting statistics
   */
  public getStatistics(): {
    hypotheses: {
      total: number;
      active: number;
      byCategory: Record<string, number>;
      byPriority: Record<string, number>;
    };
    workflows: {
      total: number;
      byStatus: Record<string, number>;
      executionRate: number;
    };
    findings: {
      total: number;
      bySeverity: Record<string, number>;
      byCategory: Record<string, number>;
      recentTrend: number;
    };
  } {
    const hypotheses = Array.from(this.hypotheses.values());
    const workflows = Array.from(this.workflows.values());
    const findings = Array.from(this.findings.values());

    return {
      hypotheses: {
        total: hypotheses.length,
        active: hypotheses.filter(h => h.status === 'active').length,
        byCategory: this.groupBy(hypotheses, 'category'),
        byPriority: this.groupBy(hypotheses, 'priority')
      },
      workflows: {
        total: workflows.length,
        byStatus: this.groupBy(workflows, 'status'),
        executionRate: workflows.filter(w => w.status === 'completed').length / Math.max(workflows.length, 1)
      },
      findings: {
        total: findings.length,
        bySeverity: this.groupBy(findings, 'severity'),
        byCategory: this.groupBy(findings, 'category'),
        recentTrend: this.calculateRecentTrend(findings)
      }
    };
  }

  // ============================================================================
  // PRIVATE METHODS
  // ============================================================================

  /**
   * Merge configuration with defaults
   */
  private mergeConfig(config?: Partial<AutomatedHuntingConfig>): AutomatedHuntingConfig {
    const defaultConfig: AutomatedHuntingConfig = {
      enabled: true,
      hypothesisGeneration: {
        enabled: true,
        frequency: 60, // 1 hour
        confidenceThreshold: 0.7,
        maxActiveHypotheses: 100,
        mlModels: []
      },
      automatedWorkflows: {
        enabled: true,
        maxConcurrentWorkflows: 5,
        defaultTimeout: 300000, // 5 minutes
        retryAttempts: 3
      },
      dataSources: {
        siem: {
          enabled: true,
          connectionString: '',
          queryTimeout: 30000,
          maxConnections: 10,
          retryPolicy: {
            maxRetries: 3,
            backoffMultiplier: 2
          }
        },
        edr: {
          enabled: true,
          connectionString: '',
          queryTimeout: 30000,
          maxConnections: 10,
          retryPolicy: {
            maxRetries: 3,
            backoffMultiplier: 2
          }
        },
        network: {
          enabled: true,
          connectionString: '',
          queryTimeout: 30000,
          maxConnections: 10,
          retryPolicy: {
            maxRetries: 3,
            backoffMultiplier: 2
          }
        },
        logs: {
          enabled: true,
          connectionString: '',
          queryTimeout: 30000,
          maxConnections: 10,
          retryPolicy: {
            maxRetries: 3,
            backoffMultiplier: 2
          }
        }
      },
      notifications: {
        enabled: true,
        channels: ['email', 'slack'],
        severityThreshold: 'high'
      }
    };

    return { ...defaultConfig, ...config };
  }

  /**
   * Load existing data from storage
   */
  private async loadExistingData(): Promise<void> {
    // Mock implementation - in production, load from database
    console.log('Loading existing hunting data...');
    
    // Load sample hypotheses
    const sampleHypotheses = await this.createSampleHypotheses();
    for (const hypothesis of sampleHypotheses) {
      this.hypotheses.set(hypothesis.id, hypothesis);
    }
    
    console.log(`Loaded ${sampleHypotheses.length} sample hypotheses`);
  }

  /**
   * Start hypothesis generation process
   */
  private startHypothesisGeneration(): void {
    const frequency = this.config.hypothesisGeneration.frequency * 60 * 1000; // Convert to milliseconds
    
    this.hypothesisGenerationInterval = setInterval(async () => {
      try {
        await this.generateHypotheses();
      } catch (error) {
        console.error('Error in hypothesis generation:', error);
      }
    }, frequency);
    
    console.log(`Hypothesis generation started with ${this.config.hypothesisGeneration.frequency} minute frequency`);
  }

  /**
   * Start workflow execution process
   */
  private startWorkflowExecution(): void {
    // Execute workflows every 5 minutes
    this.workflowExecutionInterval = setInterval(async () => {
      try {
        await this.executeWorkflows();
      } catch (error) {
        console.error('Error in workflow execution:', error);
      }
    }, 5 * 60 * 1000);
    
    console.log('Workflow execution started with 5 minute frequency');
  }

  /**
   * Start automated processes
   */
  private startAutomatedProcesses(): void {
    this.start();
  }

  /**
   * Analyze recent threat data for hypothesis generation
   */
  private async analyzeRecentThreatData(): Promise<any[]> {
    // Mock implementation - in production, analyze real threat data
    return [
      {
        timestamp: new Date(),
        type: 'malware',
        indicators: ['suspicious-process.exe', '192.168.1.100'],
        tactics: ['execution', 'persistence'],
        techniques: ['T1059', 'T1053']
      },
      {
        timestamp: new Date(),
        type: 'phishing',
        indicators: ['suspicious-domain.com', 'fake-email@company.com'],
        tactics: ['initial_access'],
        techniques: ['T1566']
      }
    ];
  }

  /**
   * Generate hypotheses using specific ML model
   */
  private async generateHypothesesWithModel(model: MLModelConfig, threatData: any[]): Promise<HuntingHypothesis[]> {
    // Mock implementation - in production, use actual ML models
    const hypotheses: HuntingHypothesis[] = [];
    
    // Generate sample hypothesis based on threat data
    if (threatData.length > 0) {
      const hypothesis = await this.createHypothesis({
        title: `ML-Generated: ${threatData[0].type} Activity Detected`,
        description: `Machine learning model identified potential ${threatData[0].type} activity based on recent threat patterns`,
        category: threatData[0].type as any,
        confidence: 0.8,
        priority: 'high',
        indicators: threatData[0].indicators,
        tactics: threatData[0].tactics,
        techniques: threatData[0].techniques
      });
      
      hypotheses.push(hypothesis);
    }
    
    return hypotheses;
  }

  /**
   * Filter and prioritize hypotheses
   */
  private filterAndPrioritizeHypotheses(hypotheses: HuntingHypothesis[]): HuntingHypothesis[] {
    const threshold = this.config.hypothesisGeneration.confidenceThreshold;
    const maxActive = this.config.hypothesisGeneration.maxActiveHypotheses;
    
    // Filter by confidence threshold
    const filtered = hypotheses.filter(h => h.confidence >= threshold);
    
    // Sort by priority and confidence
    filtered.sort((a, b) => {
      const priorityOrder = { critical: 4, high: 3, medium: 2, low: 1 };
      const priorityDiff = priorityOrder[b.priority] - priorityOrder[a.priority];
      return priorityDiff !== 0 ? priorityDiff : b.confidence - a.confidence;
    });
    
    // Limit to maximum active hypotheses
    return filtered.slice(0, maxActive);
  }

  /**
   * Get workflows ready for execution
   */
  private getWorkflowsReadyForExecution(): HuntingWorkflow[] {
    const now = new Date();
    
    return Array.from(this.workflows.values())
      .filter(w => {
        // Check if workflow is pending or scheduled for execution
        if (w.status !== 'pending' && w.status !== 'completed') {
          return false;
        }
        
        // Check if it's time for execution
        if (w.nextExecution && w.nextExecution > now) {
          return false;
        }
        
        return true;
      });
  }

  /**
   * Execute a single hunting workflow
   */
  private async executeWorkflow(workflow: HuntingWorkflow): Promise<HuntingWorkflow> {
    console.log(`Executing workflow: ${workflow.name}`);
    
    workflow.status = 'running';
    workflow.startedAt = new Date();
    this.emit('workflow:started', workflow);
    
    try {
      // Execute all queries in the workflow
      for (const query of workflow.huntQueries) {
        const execution = await this.executeQuery(query, workflow.id);
        workflow.queries.push(execution);
        
        // Analyze results and generate findings
        if (execution.status === 'completed' && execution.resultCount > 0) {
          const findings = await this.analyzeResults(execution, workflow.id);
          workflow.findings.push(...findings);
        }
      }
      
      // Calculate overall confidence
      workflow.confidence = this.calculateWorkflowConfidence(workflow);
      
      // Schedule next execution if needed
      if (workflow.schedule.frequency !== 'once') {
        workflow.nextExecution = this.calculateNextExecution(workflow.schedule);
      }
      
      workflow.status = 'completed';
      workflow.completedAt = new Date();
      
      this.emit('workflow:completed', workflow);
      console.log(`Workflow completed: ${workflow.name}`);
      
    } catch (error) {
      workflow.status = 'failed';
      this.emit('workflow:failed', workflow);
      throw error;
    }
    
    return workflow;
  }

  /**
   * Execute a single hunt query
   */
  private async executeQuery(query: HuntQuery, workflowId: string): Promise<HuntExecution> {
    const execution: HuntExecution = {
      id: crypto.randomUUID(),
      queryId: query.id,
      workflowId,
      status: 'running',
      startedAt: new Date(),
      resultCount: 0,
      executionContext: {
        dataSource: query.dataSource,
        parameters: query.parameters,
        environment: 'production'
      }
    };
    
    try {
      // Mock query execution - in production, execute actual queries
      const startTime = Date.now();
      
      // Simulate query execution
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      execution.status = 'completed';
      execution.completedAt = new Date();
      execution.duration = Date.now() - startTime;
      execution.resultCount = Math.floor(Math.random() * 100); // Mock result count
      
      console.log(`Query executed: ${query.name} (${execution.resultCount} results)`);
      
    } catch (error) {
      execution.status = 'failed';
      execution.errorMessage = error instanceof Error ? error.message : 'Unknown error';
      console.error(`Query failed: ${query.name}`, error);
    }
    
    return execution;
  }

  /**
   * Analyze query results and generate findings
   */
  private async analyzeResults(execution: HuntExecution, workflowId: string): Promise<HuntFinding[]> {
    const findings: HuntFinding[] = [];
    
    // Mock finding generation - in production, use actual analysis
    if (execution.resultCount > 10) {
      const finding: HuntFinding = {
        id: crypto.randomUUID(),
        workflowId,
        resultId: execution.id,
        title: `Suspicious Activity Detected in ${execution.executionContext.dataSource}`,
        description: `Analysis of query results revealed ${execution.resultCount} suspicious events`,
        severity: 'high',
        confidence: 0.8,
        category: 'threat_detection',
        indicators: [
          {
            type: 'ip',
            value: '192.168.1.100',
            confidence: 0.9,
            source: execution.executionContext.dataSource,
            firstSeen: new Date(),
            lastSeen: new Date(),
            context: { queryId: execution.queryId }
          }
        ],
        timeline: [
          {
            timestamp: new Date(),
            event: 'Suspicious activity detected',
            description: 'Query execution revealed anomalous patterns',
            severity: 'high',
            source: execution.executionContext.dataSource
          }
        ],
        affectedAssets: [
          {
            id: 'asset-1',
            name: 'Server-01',
            type: 'server',
            criticality: 'high',
            location: 'DataCenter-1',
            riskScore: 8.5
          }
        ],
        recommendations: [
          'Investigate the suspicious IP address',
          'Review affected systems for compromise',
          'Update security controls if confirmed'
        ],
        status: 'new',
        createdAt: new Date(),
        updatedAt: new Date()
      };
      
      findings.push(finding);
      this.findings.set(finding.id, finding);
      this.emit('finding:generated', finding);
    }
    
    return findings;
  }

  /**
   * Calculate workflow confidence based on results
   */
  private calculateWorkflowConfidence(workflow: HuntingWorkflow): number {
    if (workflow.queries.length === 0) return 0;
    
    const successfulQueries = workflow.queries.filter(q => q.status === 'completed');
    const querySuccessRate = successfulQueries.length / workflow.queries.length;
    
    const findingCount = workflow.findings.length;
    const findingScore = Math.min(findingCount / 10, 1); // Normalize to 0-1
    
    return (querySuccessRate * 0.6 + findingScore * 0.4);
  }

  /**
   * Calculate next execution time
   */
  private calculateNextExecution(schedule: HuntingWorkflow['schedule']): Date {
    const now = new Date();
    const interval = schedule.interval;
    
    switch (schedule.frequency) {
      case 'hourly':
        return new Date(now.getTime() + interval * 60 * 60 * 1000);
      case 'daily':
        return new Date(now.getTime() + interval * 24 * 60 * 60 * 1000);
      case 'weekly':
        return new Date(now.getTime() + interval * 7 * 24 * 60 * 60 * 1000);
      case 'monthly':
        return new Date(now.getTime() + interval * 30 * 24 * 60 * 60 * 1000);
      default:
        return now;
    }
  }

  /**
   * Group array items by property
   */
  private groupBy<T>(items: T[], property: keyof T): Record<string, number> {
    return items.reduce((groups, item) => {
      const key = String(item[property]);
      groups[key] = (groups[key] || 0) + 1;
      return groups;
    }, {} as Record<string, number>);
  }

  /**
   * Calculate recent trend for findings
   */
  private calculateRecentTrend(findings: HuntFinding[]): number {
    const now = new Date();
    const weekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
    
    const recentFindings = findings.filter(f => f.createdAt >= weekAgo);
    const previousWeek = findings.filter(f => {
      const twoWeeksAgo = new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000);
      return f.createdAt >= twoWeeksAgo && f.createdAt < weekAgo;
    });
    
    if (previousWeek.length === 0) return recentFindings.length > 0 ? 1 : 0;
    
    return (recentFindings.length - previousWeek.length) / previousWeek.length;
  }

  /**
   * Create sample hypotheses for demonstration
   */
  private async createSampleHypotheses(): Promise<HuntingHypothesis[]> {
    const hypotheses: HuntingHypothesis[] = [];
    
    // Sample hypothesis 1
    const hypothesis1 = await this.createHypothesis({
      title: 'Potential APT Lateral Movement Detected',
      description: 'ML models identified patterns consistent with APT lateral movement techniques',
      category: 'apt',
      confidence: 0.85,
      priority: 'high',
      indicators: ['192.168.1.50', 'suspicious-ps.exe'],
      tactics: ['lateral_movement', 'persistence'],
      techniques: ['T1021', 'T1053'],
      predictedImpact: {
        likelihood: 0.7,
        potentialDamage: 'high',
        affectedAssets: 15,
        estimatedCost: 50000
      }
    });
    
    // Sample hypothesis 2
    const hypothesis2 = await this.createHypothesis({
      title: 'Ransomware Preparation Activity',
      description: 'Behavior patterns suggest ransomware preparation activities',
      category: 'ransomware',
      confidence: 0.75,
      priority: 'critical',
      indicators: ['encrypt.exe', 'backup-deletion.bat'],
      tactics: ['impact', 'execution'],
      techniques: ['T1486', 'T1059'],
      predictedImpact: {
        likelihood: 0.9,
        potentialDamage: 'critical',
        affectedAssets: 200,
        estimatedCost: 500000
      }
    });
    
    hypotheses.push(hypothesis1, hypothesis2);
    
    return hypotheses;
  }
}

// ============================================================================
// SERVICE INSTANCE
// ============================================================================

/**
 * Global automated hunting service instance
 */
let automatedHuntingService: AutomatedHuntingService | null = null;

/**
 * Get the automated hunting service instance
 */
export function getAutomatedHuntingService(): AutomatedHuntingService {
  if (!automatedHuntingService) {
    automatedHuntingService = new AutomatedHuntingService();
  }
  return automatedHuntingService;
}

/**
 * Initialize automated hunting service with custom configuration
 */
export function initializeAutomatedHuntingService(config?: Partial<AutomatedHuntingConfig>): AutomatedHuntingService {
  automatedHuntingService = new AutomatedHuntingService(config);
  return automatedHuntingService;
}
