import { AssessmentResult } from '@/types';

export function generateIncidentReport(assessment: AssessmentResult): string {
  const date = new Date(assessment.createdAt).toUTCString();
  const verdictLabel = {
    critical: 'CRITICAL',
    high_risk: 'HIGH RISK',
    caution: 'CAUTION',
    low_risk: 'LOW RISK',
  }[assessment.verdict];

  const criticalFlags = assessment.redFlags.filter((f) => f.severity === 'critical');
  const redFlags = assessment.redFlags.filter((f) => f.severity === 'red_flag');
  const warnings = assessment.redFlags.filter((f) => f.severity === 'warning');

  let report = `TRUSTHIRE SECURITY ASSESSMENT REPORT
=====================================
Generated: ${date}
Assessment ID: ${assessment.id}
Report URL: ${process.env.NEXT_PUBLIC_APP_URL || 'https://trusthire.app'}/results/${assessment.id}

SUBJECT
-------
Recruiter Name: ${assessment.recruiterName}
Claimed Company: ${assessment.company}

RISK VERDICT: ${verdictLabel}
Final Score: ${assessment.finalScore}/100

SCORE BREAKDOWN
---------------
Identity Confidence:  ${assessment.scores.identityConfidence}/25
Employer Legitimacy:  ${assessment.scores.employerLegitimacy}/25
Process Legitimacy:   ${assessment.scores.processLegitimacy}/25
Technical Safety:     ${assessment.scores.technicalSafety}/25
`;

  if (criticalFlags.length > 0) {
    report += `
CRITICAL FLAGS (${criticalFlags.length})
${'='.repeat(40)}
`;
    for (const f of criticalFlags) {
      report += `[!] ${f.signal}\n    ${f.explanation}\n    Action: ${f.recommendation}\n\n`;
    }
  }

  if (redFlags.length > 0) {
    report += `
RED FLAGS (${redFlags.length})
${'='.repeat(40)}
`;
    for (const f of redFlags) {
      report += `[>] ${f.signal}\n    ${f.explanation}\n    Action: ${f.recommendation}\n\n`;
    }
  }

  if (warnings.length > 0) {
    report += `
WARNINGS (${warnings.length})
${'='.repeat(40)}
`;
    for (const f of warnings) {
      report += `[-] ${f.signal}\n    ${f.explanation}\n\n`;
    }
  }

  report += `
RECOMMENDED ACTIONS
-------------------
`;
  for (const step of assessment.workflowAdvice) {
    report += `[${step.priority.toUpperCase()}] ${step.description}\n`;
  }

  report += `
REPORTING RESOURCES
-------------------
- GitHub Abuse: https://github.com/contact/report-abuse
- LinkedIn Report: https://www.linkedin.com/help/linkedin/answer/a1340567
- DNSC Romania: https://dnsc.ro
- CISA USA: https://www.cisa.gov/report
- FBI IC3: https://www.ic3.gov

DISCLAIMER
----------
This report is generated by TrustHire based on heuristic analysis and
manual input. It represents a risk assessment, not a legal verdict.
Scores indicate confidence levels, not definitive proof of malicious intent.
Always verify information through official channels before taking action.
`;

  return report;
}
